/**
 * ============================================
 * WAITLESS — Push Notification Client Service
 * ============================================
 *
 * FILE: src/lib/pushService.js
 *
 * Handles the patron-side push subscription flow:
 *   1. Detect whether this browser supports web push
 *   2. Ask the patron for notification permission (if not already decided)
 *   3. Subscribe to the browser's push manager
 *   4. POST the subscription to our DB so send-push.js can target this device
 *
 * Imported by App.jsx on the confirmation screen.
 *
 * BROWSER SUPPORT REALITY:
 *   - Desktop Chrome/Edge/Firefox/Safari 16+      → works fine
 *   - Android Chrome/Firefox                      → works fine
 *   - iOS Safari (browser tab)                    → push NOT supported, period
 *   - iOS Safari (PWA installed to home screen)   → works since iOS 16.4
 *
 * We use isPushSupported() to detect upfront and hide the "Enable
 * notifications" button on devices where it won't work — better than
 * silently failing or showing a confusing error.
 *
 * ============================================
 * IMPORTANT: VAPID public key must match what's in Netlify env vars
 * (VAPID_PUBLIC_KEY). If they don't match, browsers will accept the
 * subscription but send-push.js won't be able to deliver notifications.
 * ============================================
 */

import { supabase } from "./barOrderService";

// ============================================================================
// ⚠️ REPLACE THIS WITH YOUR ACTUAL VAPID PUBLIC KEY
// ============================================================================
// The public key you generated with `npx web-push generate-vapid-keys`.
// Same value as the VAPID_PUBLIC_KEY env var in Netlify.
//
// This IS the public key — it's safe to commit to git. The PRIVATE key
// (also generated by that command) stays server-side only in Netlify env.
//
// Format: base64url-encoded, ~88 characters, starts with "B"
// ============================================================================
const VAPID_PUBLIC_KEY = "BApgBJtV_08WF-A6zjcIL33pllxlFdw4NavlMx9X3-I0OWdXnTaHQeJPh-PtWnA6rJy7ozim-Luj9ZmX2TW2EMg";

// ============================================================================
// FEATURE DETECTION
// ============================================================================

/**
 * Returns true if this browser can receive web push notifications.
 *
 * The check is intentionally conservative: a device passes only if ALL of
 * 'serviceWorker', 'PushManager', and 'Notification' APIs exist. iOS Safari
 * lies about some of these in unusual states (e.g. private browsing), so
 * we re-check at subscribe time too.
 */
export function isPushSupported() {
  if (typeof window === "undefined") return false;
  return (
    "serviceWorker" in navigator &&
    "PushManager" in window &&
    "Notification" in window
  );
}

/**
 * Returns the current notification permission state for this origin.
 * Possible values:
 *   "default" — patron has never been asked; safe to prompt
 *   "granted" — patron previously said yes
 *   "denied"  — patron previously said no; cannot prompt again (browser
 *               will silently ignore requestPermission() calls)
 *   "unsupported" — push not available on this device at all
 */
export function getPermissionState() {
  if (!isPushSupported()) return "unsupported";
  return Notification.permission;
}

// ============================================================================
// VAPID KEY HELPER
// ============================================================================

/**
 * The browser's pushManager.subscribe() needs the VAPID public key as a
 * Uint8Array, not a base64url string. This converts it.
 *
 * Standard helper recommended by every web-push tutorial. Lifted as-is
 * because the math is annoying and easy to get subtly wrong.
 */
function urlBase64ToUint8Array(base64String) {
  const padding = "=".repeat((4 - (base64String.length % 4)) % 4);
  const base64 = (base64String + padding).replace(/-/g, "+").replace(/_/g, "/");
  const rawData = atob(base64);
  const outputArray = new Uint8Array(rawData.length);
  for (let i = 0; i < rawData.length; ++i) {
    outputArray[i] = rawData.charCodeAt(i);
  }
  return outputArray;
}

// ============================================================================
// SUBSCRIBE TO PUSH FOR THIS ORDER
// ============================================================================

/**
 * Asks for notification permission (if needed), creates a push subscription,
 * and saves it to the push_subscriptions table linked to this order.
 *
 * RETURNS:
 *   { ok: true }                            — subscribed successfully
 *   { ok: false, reason: "unsupported" }    — device can't do push at all
 *   { ok: false, reason: "denied" }         — patron blocked notifications
 *   { ok: false, reason: "no_vapid_key" }   — VAPID_PUBLIC_KEY not set (dev oops)
 *   { ok: false, reason: "subscribe_failed", error } — browser refused
 *   { ok: false, reason: "save_failed", error }     — DB insert errored
 *
 * The caller (App.jsx confirmation screen) decides what UI to show based on
 * the reason. We return structured failures instead of throwing because
 * "patron tapped Block" isn't really an exception — it's a normal outcome.
 *
 * SAFETY:
 *   - Idempotent: calling it twice for the same (order, device) is a no-op
 *     thanks to the unique index on (order_id, endpoint) in the DB.
 *   - Reuses an existing PushSubscription if the browser already has one
 *     for this domain — doesn't force the browser to mint a new one.
 */
export async function subscribeOrderToPush({ orderId, venueId }) {
  if (!isPushSupported()) {
    return { ok: false, reason: "unsupported" };
  }
  if (!VAPID_PUBLIC_KEY || VAPID_PUBLIC_KEY.startsWith("REPLACE_ME")) {
    console.error("VAPID_PUBLIC_KEY not configured in pushService.js");
    return { ok: false, reason: "no_vapid_key" };
  }
  if (!orderId || !venueId) {
    return { ok: false, reason: "missing_args" };
  }

  // Permission gate. If denied, we can't ask again — the browser silently
  // refuses requestPermission() calls after a denial.
  if (Notification.permission === "denied") {
    return { ok: false, reason: "denied" };
  }
  if (Notification.permission === "default") {
    const result = await Notification.requestPermission();
    if (result !== "granted") {
      return { ok: false, reason: "denied" };
    }
  }
  // At this point we have permission. Proceed.

  // Get the active service worker registration. sw.js was registered in
  // main.jsx at app startup, so this should resolve immediately.
  let registration;
  try {
    registration = await navigator.serviceWorker.ready;
  } catch (err) {
    console.error("Service worker not ready:", err);
    return { ok: false, reason: "subscribe_failed", error: err };
  }

  // Try to reuse an existing subscription for this device first. If the
  // patron has subscribed on a previous order, the browser still has the
  // subscription object — we don't need to mint a new one, just link it
  // to the new order_id in our DB.
  let subscription;
  try {
    subscription = await registration.pushManager.getSubscription();
    if (!subscription) {
      subscription = await registration.pushManager.subscribe({
        userVisibleOnly: true,
        applicationServerKey: urlBase64ToUint8Array(VAPID_PUBLIC_KEY),
      });
    }
  } catch (err) {
    console.error("PushManager.subscribe failed:", err);
    return { ok: false, reason: "subscribe_failed", error: err };
  }

  // Extract the parts our DB needs
  const subJson = subscription.toJSON();
  const endpoint = subJson.endpoint;
  const p256dh = subJson.keys?.p256dh;
  const auth = subJson.keys?.auth;

  if (!endpoint || !p256dh || !auth) {
    console.error("Subscription missing required fields:", subJson);
    return { ok: false, reason: "subscribe_failed" };
  }

  // Save it to Supabase. The unique index on (order_id, endpoint) means a
  // duplicate insert (e.g. patron tapped twice) will fail with a 409 — we
  // catch that and treat it as success since "already subscribed" is fine.
  const { error: insertErr } = await supabase
    .from("push_subscriptions")
    .insert({
      order_id: orderId,
      venue_id: venueId,
      endpoint,
      p256dh_key: p256dh,
      auth_key: auth,
      user_agent: typeof navigator !== "undefined" ? navigator.userAgent : null,
    });

  if (insertErr) {
    // 23505 = unique violation = "already exists" = fine, this device is already
    // subscribed for this order. Treat as success.
    if (insertErr.code === "23505") {
      return { ok: true, alreadySubscribed: true };
    }
    console.error("push_subscriptions insert failed:", insertErr);
    return { ok: false, reason: "save_failed", error: insertErr };
  }

  return { ok: true };
}

// ============================================================================
// (Optional, deferred) UNSUBSCRIBE
// ============================================================================
// Not used in v1 because per-order subscriptions auto-cleanup via DB cascade
// when orders go terminal, and via send-push.js when the push service
// returns 410. If we ever add a "Stop notifying me" button in the UI, this
// is where it would live. Leaving stub commented-out for future reference.
//
// export async function unsubscribeOrderFromPush({ orderId }) {
//   await supabase.from("push_subscriptions").delete().eq("order_id", orderId);
// }
